### PR TITLE
Fixes rubocop litteral comment

### PR DESCRIPTION
**Pull request by jjasghar**

### CODE REVIEW

**Comment by jjasghar** [comment]
Bump.

**Comment by tmclaugh** [comment]
I can't reproduce your failures that spawned this PR in Travis.

https://travis-ci.org/threatstack/threatstack-chef/builds/168354477

What's different?  We have rubocop locked so that shouldn't be it.

**Comment by jjasghar** [comment]
It looks like we are pulling in the same version of `Installing rubocop 0.43.0`: https://jenkins-01.eastus.cloudapp.azure.com/job/threatstack-cookbook/104/console

I'm not sure what's going on.

**Comment by jjasghar** [comment]
https://travis-ci.org/threatstack/threatstack-chef/jobs/168354478#L247

**Comment by tmclaugh** [comment]
I thought maybe Ruby 2.2 v 2.3 triggered something but not the case.going to compare gem versions now.

**Pull request closed without merging**
