### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jjasghar**
Added the build badge per the new Chef Partner cookbook guide guidelines.

### CODE REVIEW

**Comment by jjasghar** [comment]
I've also updated the chefdk, and it looks yall have some rubocop issues: https://jenkins-01.eastus.cloudapp.azure.com/job/threatstack-cookbook/lastFailedBuild/console

**Comment by jjasghar** [comment]
Hmmm... more errors.

https://jenkins-01.eastus.cloudapp.azure.com/job/threatstack-cookbook/94/console

**Comment by tmclaugh** [comment]
I'll be doing cleanup this week.

**Comment by jjasghar** [comment]
Awesome thanks!

**Comment by tmclaugh** [comment]
@jjasghar can you elaborate on the issue?  It looks like the tests are failing due to an openssl error and I don't understand what is causing that.

      OpenSSL::SSL::SSLError:
        SSL Error connecting to https://localhost/nodes/fauxhai.local - hostname "localhost" does not match the server certificate

**Comment by jjasghar** [comment]
Looking into this, it seems it's an oddity with `chef-zero` and `chefspec`.

I'm honestly not sure how to fix it, but i am investing.

**Comment by tmclaugh** [comment]
@jjasghar I have #34 which has some updates and is passing or Travis build now.

https://travis-ci.org/threatstack/threatstack-chef/builds/167100046

I dropped testing < Chef 12.5 so I could get some dependencies updated.  Are there any particular milestone versions you feel we should be testing?  Right now these are the version I expect to test when we push.

https://github.com/threatstack/threatstack-chef/blob/a13a2e8ae73f02a4a48548893de9521d18dd987c/.travis.yml#L12-L15

**Comment by jjasghar** [comment]
perfect, commented on that PR thanks!

**Comment by tmclaugh** [comment]
I've merged #34 but don't want to merge this until the tests pass on your side.  master is now passing our travis builds.

**Comment by jjasghar** [comment]
It looks like that you havent pinned `rubocop`.

```
[threatstack-cookbook] $ /bin/bash /tmp/hudson6789940221691810252.sh
direnv: loading ~/.direnvrc
direnv: loading .envrc
direnv: export +BUNDLE_BIN +RUBYOPT ~GEM_HOME ~PATH
RuboCop failed!
Starting Foodcritic linting...
Completed!
Running RuboCop...
Inspecting 10 files
CCCCCCCCCC

Offenses:

Berksfile:1:1: C: Missing frozen string literal comment.
source 'https://supermarket.getchef.com'
^
attributes/default.rb:1:1: C: Missing frozen string literal comment.
#
^
attributes/repo.rb:1:1: C: Missing frozen string literal comment.
default['threatstack']['repo_enable'] = true
^
recipes/debian.rb:1:1: C: Missing frozen string literal comment.
#
^
recipes/default.rb:1:1: C: Missing frozen string literal comment.
#
^
recipes/rhel.rb:1:1: C: Missing frozen string literal comment.
#
^
spec/default_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/repo_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/spec_helper.rb:1:1: C: Missing frozen string literal comment.
# spec_helper.rb
^
test/integration/default/serverspec/default_spec.rb:1:1: C: Missing frozen string literal comment.
# Encoding: utf-8
^

10 files inspected, 10 offenses detected
Build step 'Execute shell' marked build as failure
Performing Post build task...
Could not match :Class: Kitchen::ActionFailed  : False
Logical operation result is FALSE
Skipping script  : #!/bin/bash
KITCHEN_YAML=".kitchen.azure.yml" chef exec kitchen list
KITCHEN_YAML=".kitchen.azure.yml" chef exec kitchen destroy

END OF POST BUILD TASK 	: 0
Finished: FAILURE
```

**Comment by jjasghar** [comment]
I do a `bundle` every time to make sure that the `Gemfile` and `Gemfile.lock` are up to date :)

**Comment by jjasghar** [comment]
https://github.com/threatstack/threatstack-chef/pull/35

**Pull request closed without merging**
